# Generated by Django 3.2.16 on 2023-02-08 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('c0', models.IntegerField()),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField()),
                ('c4', models.IntegerField()),
                ('c5', models.IntegerField()),
                ('c6', models.IntegerField()),
                ('c7', models.IntegerField()),
                ('c8', models.IntegerField()),
                ('c9', models.IntegerField()),
                ('c10', models.IntegerField()),
                ('c11', models.IntegerField()),
                ('c12', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bas_ym', models.IntegerField()),
                ('age_dc', models.CharField(max_length=10)),
                ('gender', models.IntegerField()),
                ('bas_dt', models.IntegerField()),
                ('tran_md', models.CharField(max_length=45)),
                ('ats_kdcd_dtl', models.CharField(max_length=45)),
                ('dps_trn_am', models.IntegerField(blank=True, null=True)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=45, null=True)),
                ('user_info_uid', models.ForeignKey(db_column='user_info_uid', on_delete=django.db.models.deletion.DO_NOTHING, to='un_tran_report.userinfo')),
            ],
            options={
                'db_table': 'transaction',
                'managed': True,
                'unique_together': {('id', 'user_info_uid')},
            },
        ),
    ]
