# Generated by Django 3.2.16 on 2023-01-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=45, unique=True)),
                ('c0', models.IntegerField(default=0)),
                ('c1', models.IntegerField(default=0)),
                ('c2', models.IntegerField(default=0)),
                ('c3', models.IntegerField(default=0)),
                ('c4', models.IntegerField(default=0)),
                ('c5', models.IntegerField(default=0)),
                ('c6', models.IntegerField(default=0)),
                ('c7', models.IntegerField(default=0)),
                ('c8', models.IntegerField(default=0)),
                ('c9', models.IntegerField(default=0)),
                ('c10', models.IntegerField(default=0)),
                ('c11', models.IntegerField(default=0)),
                ('c12', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
