# Generated by Django 3.2.16 on 2023-01-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_tran_report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnTranReportUserinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=45, unique=True)),
                ('c0', models.IntegerField()),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField()),
                ('c4', models.IntegerField()),
                ('c5', models.IntegerField()),
                ('c6', models.IntegerField()),
                ('c7', models.IntegerField()),
                ('c8', models.IntegerField()),
                ('c9', models.IntegerField()),
                ('c10', models.IntegerField()),
                ('c11', models.IntegerField()),
                ('c12', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'un_tran_report_userinfo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
