# Generated by Django 3.2.16 on 2023-01-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('un_tran_report', '0002_auto_20230130_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bas_ym', models.IntegerField()),
                ('age_dc', models.CharField(max_length=10)),
                ('gender', models.IntegerField()),
                ('bas_dt', models.IntegerField()),
                ('tran_md', models.CharField(max_length=3)),
                ('ats_kdcd_dtl', models.CharField(max_length=45)),
                ('dps_trn_am', models.IntegerField(blank=True, null=True)),
                ('text_1', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('c0', models.IntegerField()),
                ('c1', models.IntegerField()),
                ('c2', models.IntegerField()),
                ('c3', models.IntegerField()),
                ('c4', models.IntegerField()),
                ('c5', models.IntegerField()),
                ('c6', models.IntegerField()),
                ('c7', models.IntegerField()),
                ('c8', models.IntegerField()),
                ('c9', models.IntegerField()),
                ('c10', models.IntegerField()),
                ('c11', models.IntegerField()),
                ('c12', models.IntegerField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UnTranReportUserinfo',
        ),
    ]
